### ISSUE TITLE
Problème avec Get-AdGroupMembershipChange

### ISSUE THREAD

**Issue by basox70** [florianburnel/PowerShell#2]
Bonjour,
J'ai une erreur lors de l'exécution du script : 
"D:\Documents\Scripts\Get-AdGroupMembershipChange.ps1 : Impossible de lier l'argument au paramètre « ExportASHTML », car il s'agit d'une chaîne vide"

Je pense que ça viens de la ligne 55 : 
[Parameter(Mandatory)][string]$ExportASHTML = "$PsScriptRoot\AdGroupMembershipChange.html"
car le paramètre n'est pas défini

**Comment by basox70** [comment]
la comma

**Comment by florianburnel** [comment]
Bonjour,

Désolé j'avais pas du tout fait attention cette issue... J'ai remarqué le même problème il y a peu, j'ai retiré l'option mandatory sur le paramètre pour pas qu'il soit obligatoire. Ce n'est plus gênant maintenant.

Bonne soirée
Florian
